#pragma once


#include <cstdint>

enum disc_permissions_type : uint64_t {
	PERM_CREATE_INSTANT_INVITE      = (1LL << 0),
	PERM_KICK_MEMBERS               = (1LL << 1),
	PERM_BAN_MEMBERS                = (1LL << 2),
	PERM_ADMINISTRATOR              = (1LL << 3),
	PERM_MANAGE_CHANNELS            = (1LL << 4),
	PERM_MANAGE_GUILD               = (1LL << 5),
	PERM_ADD_REACTIONS              = (1LL << 6),
	PERM_VIEW_AUDIT_LOG             = (1LL << 7),
	PERM_PRIORITY_SPEAKER           = (1LL << 8),
	PERM_STREAM                     = (1LL << 9),
	PERM_VIEW_CHANNEL               = (1LL << 10),
	PERM_SEND_MESSAGES              = (1LL << 11),
	PERM_SEND_TTS_MESSAGES          = (1LL << 12),
	PERM_MANAGE_MESSAGES            = (1LL << 13),
	PERM_EMBED_LINKS                = (1LL << 14),
	PERM_ATTACH_FILES               = (1LL << 15),
	PERM_READ_MESSAGE_HISTORY       = (1LL << 16),
	PERM_MENTION_EVERYONE           = (1LL << 17),
	PERM_USE_EXTERNAL_EMOJIS        = (1LL << 18),
	PERM_VIEW_GUILD_INSIGHTS        = (1LL << 19),
	PERM_CONNECT                    = (1LL << 20),
	PERM_SPEAK                      = (1LL << 21),
	PERM_MUTE_MEMBERS               = (1LL << 22),
	PERM_DEAFEN_MEMBERS             = (1LL << 23),
	PERM_MOVE_MEMBERS               = (1LL << 24),
	PERM_USE_VAD                    = (1LL << 25),
	PERM_CHANGE_NICKNAME            = (1LL << 26),
	PERM_MANAGE_NICKNAMES           = (1LL << 27),
	PERM_MANAGE_ROLES               = (1LL << 28),
	PERM_MANAGE_WEBHOOKS            = (1LL << 29),
	PERM_MANAGE_EMOJIS_AND_STICKERS = (1LL << 30),
	PERM_USE_APPLICATION_COMMANDS   = (1LL << 31),
	PERM_REQUEST_TO_SPEAK           = (1LL << 32),
	PERM_MANAGE_THREADS             = (1LL << 34),
	PERM_USE_PUBLIC_THREADS         = (1LL << 35),
	PERM_USE_PRIVATE_THREADS        = (1LL << 36),
	PERM_USE_EXTERNAL_STICKERS      = (1LL << 37),
};
